"""Markdown report helpers for survey analysis collection."""

from __future__ import annotations

import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def format_float(value: float) -> str:
    """Format numeric survey metrics compactly for Markdown tables."""
    if (
        math.isfinite(value)
        and value != 0.0
        and (abs(value) >= 1e4 or abs(value) < 1e-3)
    ):
        return f"{value:.6e}"
    return f"{value:.6f}".rstrip("0").rstrip(".")


def write_survey_report(
    report_path: Path,
    *,
    survey_dir: Path,
    total_runs: int,
    summaries_collected: int,
    generated_summaries: int,
    missing_summaries: int,
    readiness_counts: dict[str, int],
    readiness_issues: list[dict[str, Any]],
    state_counts: dict[str, int],
    numeric_stats: dict[str, dict[str, float]],
    figures: list[dict[str, str]],
    warnings: list[str],
) -> None:
    """Write the Markdown survey collection report."""
    lines: list[str] = [
        "# Survey Summary",
        "",
        f"- Survey directory: `{survey_dir}`",
        f"- Generated at: `{datetime.now(timezone.utc).isoformat(timespec='seconds')}`",
        f"- Total runs: {total_runs}",
        f"- Summaries collected: {summaries_collected}",
        f"- Summaries auto-generated by collect: {generated_summaries}",
        f"- Runs missing summary.json: {missing_summaries}",
        "",
        "## State Counts",
        "",
    ]

    if state_counts:
        for state, count in sorted(state_counts.items()):
            lines.append(f"- `{state}`: {count}")
    else:
        lines.append("- No manifest states found.")

    lines.extend(["", "## Analysis Readiness", ""])
    if readiness_counts:
        for status, count in sorted(readiness_counts.items()):
            lines.append(f"- `{status}`: {count}")
    else:
        lines.append("- No readiness diagnostics were available.")

    if readiness_issues:
        lines.extend(["", "### Runs Requiring Attention", ""])
        for issue in readiness_issues:
            missing = issue.get("missing_required_artifacts", [])
            missing_text = ", ".join(missing) if missing else "none"
            warnings_text = "; ".join(issue.get("warnings", [])) or "not ready"
            lines.append(
                f"- `{issue.get('run_id', '')}`: "
                f"{issue.get('analysis_status', 'unknown')} "
                f"(missing: {missing_text}) - {warnings_text}"
            )

    lines.extend(["", "## Numeric Metrics", ""])
    if numeric_stats:
        lines.append("| metric | count | min | max | mean |")
        lines.append("| --- | ---: | ---: | ---: | ---: |")
        for metric, stats in sorted(numeric_stats.items()):
            lines.append(
                "| "
                f"{metric} | {int(stats['count'])} | {format_float(stats['min'])}"
                f" | {format_float(stats['max'])} | {format_float(stats['mean'])} |"
            )
    else:
        lines.append("No numeric scalar metrics were found across collected summaries.")

    lines.extend(["", "## Figures", ""])
    if figures:
        for fig in figures:
            caption = f" - {fig['caption']}" if fig["caption"] else ""
            lines.append(f"- `{fig['run_id']}`: `{fig['path']}`{caption}")
    else:
        lines.append("No figure artifacts were indexed.")

    if warnings:
        lines.extend(["", "## Warnings", ""])
        for warning in warnings:
            lines.append(f"- {warning}")

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
