"""CLI command for updating reference repositories and knowledge indexes."""

from __future__ import annotations

import logging
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Annotated, Optional

import typer

from runops.adapters.base import SimulatorAdapter
from runops.core.exceptions import SimctlError
from runops.core.project import find_project_root, load_project

logger = logging.getLogger(__name__)

_SIMCTL_DIR = ".runops"
_KNOWLEDGE_DIR = "knowledge"


def _get_commit_hash(repo_path: Path) -> str | None:
    """Get current HEAD commit hash of a git repo."""
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo_path),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode == 0:
        return result.stdout.strip()
    return None


def _detect_remote_ref(repo_path: Path) -> str:
    """Detect the remote branch to reset to after fetch."""
    # Try origin/HEAD first
    result = subprocess.run(
        ["git", "rev-parse", "--verify", "origin/HEAD"],
        cwd=str(repo_path),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode == 0:
        return "origin/HEAD"

    # Try origin/main, origin/master
    for branch in ("origin/main", "origin/master"):
        result = subprocess.run(
            ["git", "rev-parse", "--verify", branch],
            cwd=str(repo_path),
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return branch

    return "FETCH_HEAD"


def _pull_shallow(repo_path: Path) -> tuple[str | None, str | None, str]:
    """Fetch and reset a shallow clone.

    Returns:
        Tuple of (old_hash, new_hash, message).
    """
    old_hash = _get_commit_hash(repo_path)

    fetch = subprocess.run(
        ["git", "fetch", "--depth", "1", "origin"],
        cwd=str(repo_path),
        capture_output=True,
        text=True,
        check=False,
    )
    if fetch.returncode != 0:
        msg = f"git fetch failed: {fetch.stderr.strip()}"
        logger.warning("%s: %s", repo_path.name, msg)
        return old_hash, old_hash, msg

    remote_ref = _detect_remote_ref(repo_path)

    reset = subprocess.run(
        ["git", "reset", "--hard", remote_ref],
        cwd=str(repo_path),
        capture_output=True,
        text=True,
        check=False,
    )
    if reset.returncode != 0:
        msg = f"git reset failed: {reset.stderr.strip()}"
        logger.warning("%s: %s", repo_path.name, msg)
        return old_hash, old_hash, msg

    new_hash = _get_commit_hash(repo_path)

    if old_hash == new_hash:
        return old_hash, new_hash, "already up-to-date"
    return old_hash, new_hash, "updated"


def _collect_knowledge_files(
    refs_dir: Path, repo_name: str, patterns: list[str]
) -> list[str]:
    """Collect files matching glob patterns in a repo directory."""
    repo_path = refs_dir / repo_name
    if not repo_path.is_dir():
        return []
    files: list[str] = []
    seen: set[str] = set()
    for pattern in patterns:
        for match in sorted(repo_path.glob(pattern)):
            if match.is_file():
                rel = match.relative_to(repo_path).as_posix()
                if rel not in seen:
                    seen.add(rel)
                    files.append(rel)
    return files


def _read_existing_changelog(knowledge_file: Path) -> list[str]:
    """Read existing change log entries from a knowledge file."""
    if not knowledge_file.is_file():
        return []
    entries: list[str] = []
    in_changelog = False
    for line in knowledge_file.read_text(encoding="utf-8").split("\n"):
        if line.strip() == "## Change Log":
            in_changelog = True
            continue
        if in_changelog:
            if line.startswith("## "):
                break
            stripped = line.strip()
            if stripped.startswith("- "):
                entries.append(stripped)
    return entries


def _generate_knowledge_md(
    simulator_name: str,
    sources: dict[str, list[str]],
    commits: dict[str, str | None],
    changes: dict[str, tuple[str | None, str | None]],
    existing_changelog: list[str],
) -> str:
    """Generate .runops/knowledge/{simulator}.md content."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Knowledge Index: {simulator_name}",
        "",
        f"Auto-generated by `runo update-refs` on {now}",
        "",
    ]

    for repo_name, file_list in sources.items():
        commit = commits.get(repo_name) or "unknown"
        short = commit[:8] if len(commit) >= 8 else commit
        lines.append(f"## {repo_name}")
        lines.append("")
        lines.append(f"**Commit**: `{short}`")
        lines.append("")
        if file_list:
            lines.append("### Files")
            lines.append("")
            for f in file_list:
                lines.append(f"- `refs/{repo_name}/{f}`")
            lines.append("")
        else:
            lines.append("No knowledge source files found.")
            lines.append("")

    # Build change log: new entries + existing
    new_entries: list[str] = []
    for repo_name, (old, new) in changes.items():
        if old and new and old != new:
            old_short = old[:8]
            new_short = new[:8]
            new_entries.append(f"- {now}: {repo_name} (`{old_short}` -> `{new_short}`)")

    all_entries = new_entries + existing_changelog
    if all_entries:
        lines.append("## Change Log")
        lines.append("")
        # Keep last 20 entries
        for entry in all_entries[:20]:
            lines.append(entry)
        lines.append("")

    return "\n".join(lines)


def _get_project_simulators() -> tuple[Path, dict[str, str]]:
    """Find project root and return {sim_name: adapter_name} mapping."""
    cwd = Path.cwd().resolve()
    root = find_project_root(cwd)
    project = load_project(root)
    mapping: dict[str, str] = {}
    for sim_name, sim_cfg in project.simulators.items():
        adapter_name = sim_cfg.get("adapter", sim_name)
        mapping[sim_name] = adapter_name
    return root, mapping


def _get_adapter_class(adapter_name: str) -> type[SimulatorAdapter] | None:
    """Get adapter class by adapter name (not simulator entry name)."""
    import runops.adapters  # noqa: F401
    from runops.adapters.registry import get_global_registry

    registry = get_global_registry()
    try:
        return registry.get(adapter_name)
    except KeyError:
        return None


def update_refs(
    simulators: Annotated[
        Optional[list[str]],
        typer.Argument(help="Simulators to update (defaults to all in project)."),
    ] = None,
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Show what would be updated."),
    ] = False,
) -> None:
    """Update optional reference mirrors (refs/) and knowledge indexes.

    Fetches the latest commits for simulator reference repositories that were
    cloned with ``runo init --with-refs`` or managed manually, then rebuilds
    the .runops/knowledge/ index files.

    Examples:
      runo update-refs            # update all local refs mirrors
      runo update-refs emses      # update only EMSES refs mirror
      runo update-refs --dry-run  # show what would be updated
    """
    try:
        root, project_sims = _get_project_simulators()
    except SimctlError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(code=1) from None

    # project_sims is {sim_name: adapter_name}
    # If user passes simulator names, resolve to adapter names
    if simulators:
        target_mapping: dict[str, str] = {}
        for s in simulators:
            if s in project_sims:
                target_mapping[s] = project_sims[s]
            else:
                # Maybe user passed adapter name directly
                target_mapping[s] = s
    else:
        target_mapping = dict(project_sims)

    if not target_mapping:
        typer.echo("No simulators found in project.")
        raise typer.Exit(code=1)

    refs_dir = root / "refs"
    knowledge_dir = root / _SIMCTL_DIR / _KNOWLEDGE_DIR

    # Collect all repos to update from adapters
    repos_to_update: dict[str, str] = {}  # dest_name -> sim_name (for display)
    sim_sources: dict[str, dict[str, list[str]]] = {}  # sim -> {repo -> patterns}

    for sim_name, adapter_name in target_mapping.items():
        adapter_cls = _get_adapter_class(adapter_name)
        if adapter_cls is None:
            typer.echo(
                f"  Warning: no adapter '{adapter_name}' for '{sim_name}', skipping."
            )
            continue

        # Get doc repos for this adapter
        doc_repos = adapter_cls.doc_repos()
        knowledge = adapter_cls.knowledge_sources()

        for _url, dest in doc_repos:
            repos_to_update[dest] = sim_name

        if knowledge:
            sim_sources[adapter_name] = knowledge
        else:
            # Default: index docs/ and README from each doc repo
            sim_sources[adapter_name] = {
                dest: ["README.md", "docs/**/*.md"] for _url, dest in doc_repos
            }

    if not repos_to_update:
        typer.echo("No reference repos configured for the selected simulators.")
        return

    if dry_run:
        typer.echo("Would update the following repos:")
        for dest in sorted(repos_to_update):
            repo_path = refs_dir / dest
            exists = repo_path.is_dir()
            status = "exists" if exists else "not cloned"
            typer.echo(f"  refs/{dest}/ ({status})")
        typer.echo("\nWould regenerate knowledge indexes:")
        for sim_name in sorted(sim_sources):
            typer.echo(f"  .runops/knowledge/{sim_name}.md")
        return

    # Phase 1: Pull repos
    typer.echo("Updating reference repos...")
    all_changes: dict[str, tuple[str | None, str | None]] = {}
    all_commits: dict[str, str | None] = {}

    for dest in sorted(repos_to_update):
        repo_path = refs_dir / dest
        if not repo_path.is_dir():
            typer.echo(
                f"  refs/{dest}/ — not cloned, skipping "
                "(run 'runo init --with-refs' first or clone it manually)"
            )
            continue

        old_hash, new_hash, msg = _pull_shallow(repo_path)
        all_changes[dest] = (old_hash, new_hash)
        all_commits[dest] = new_hash

        if old_hash != new_hash:
            old_short = (old_hash or "")[:8]
            new_short = (new_hash or "")[:8]
            typer.echo(f"  refs/{dest}/ — updated ({old_short} -> {new_short})")
        else:
            typer.echo(f"  refs/{dest}/ — {msg}")

    # Phase 2: Generate knowledge indexes
    typer.echo("\nRegenerating knowledge indexes...")
    knowledge_dir.mkdir(parents=True, exist_ok=True)

    for sim_name, repo_patterns in sorted(sim_sources.items()):
        knowledge_file = knowledge_dir / f"{sim_name}.md"

        # Collect files for each repo
        sources: dict[str, list[str]] = {}
        for repo_name, patterns in repo_patterns.items():
            files = _collect_knowledge_files(refs_dir, repo_name, patterns)
            sources[repo_name] = files

        # Read existing changelog to preserve history
        existing_changelog = _read_existing_changelog(knowledge_file)

        # Filter changes to only this simulator's repos
        sim_changes = {
            repo: change
            for repo, change in all_changes.items()
            if repo in repo_patterns
        }
        sim_commits = {
            repo: commit
            for repo, commit in all_commits.items()
            if repo in repo_patterns
        }

        content = _generate_knowledge_md(
            sim_name, sources, sim_commits, sim_changes, existing_changelog
        )
        knowledge_file.write_text(content)

        total_files = sum(len(f) for f in sources.values())
        typer.echo(f"  .runops/knowledge/{sim_name}.md — {total_files} files indexed")

    typer.echo("\nDone.")
