"""Render helpers for generated knowledge imports."""

from __future__ import annotations

from pathlib import Path

from runops.core.exceptions import KnowledgeSourceError
from runops.core.knowledge_source import (
    KnowledgeConfig,
    KnowledgeSource,
    _dedupe_strings,
    _mount_path,
    _resolve_import_target,
    load_entrypoints,
)


def _resolve_profile_imports(
    source_path: Path,
    source: KnowledgeSource,
) -> list[str]:
    manifest = load_entrypoints(source_path)
    imports = list(manifest.imports) if manifest is not None else []

    if source.profiles:
        for profile_name in source.profiles:
            if manifest is not None and profile_name in manifest.profile_imports:
                imports.extend(manifest.profile_imports[profile_name])
            else:
                imports.append(f"profiles/{profile_name}.md")
    elif not imports and (source_path / "CLAUDE.md").is_file():
        imports.append("CLAUDE.md")

    return _dedupe_strings(imports)


def render_imports(
    project_root: Path,
    config: KnowledgeConfig,
    *,
    extra_imports: list[str] | None = None,
) -> Path:
    """Generate imports.md from enabled profiles."""
    enabled_dir = project_root / config.derived_dir / "enabled"
    enabled_dir.mkdir(parents=True, exist_ok=True)
    imports_path = enabled_dir / "imports.md"

    lines: list[str] = [
        "<!-- Auto-generated by runops knowledge source render. Do not edit. -->",
        "",
    ]

    rendered_paths: set[str] = set()
    for source in config.sources:
        if source.kind != "profiles":
            continue

        mount_path = _mount_path(project_root, source)
        if mount_path is None:
            lines.append(f"<!-- source {source.name}: mount not configured -->")
            continue
        if not mount_path.is_dir():
            lines.append(f"<!-- source {source.name}: not mounted -->")
            continue

        try:
            source_imports = _resolve_profile_imports(mount_path, source)
        except KnowledgeSourceError as exc:
            lines.append(f"<!-- source {source.name}: invalid entrypoints ({exc}) -->")
            continue

        if not source_imports:
            lines.append(f"<!-- source {source.name}: no entrypoints enabled -->")
            continue

        for rel_path in source_imports:
            try:
                resolved = _resolve_import_target(mount_path, rel_path)
            except KnowledgeSourceError as exc:
                lines.append(f"<!-- source {source.name}: {exc} -->")
                continue
            if not resolved.is_file():
                profile_match = rel_path.startswith("profiles/") and rel_path.endswith(
                    ".md"
                )
                if profile_match:
                    profile_name = Path(rel_path).stem
                    lines.append(
                        f"<!-- profile {profile_name} not found in {source.name} -->"
                    )
                else:
                    lines.append(
                        f"<!-- source {source.name}: missing import target "
                        f"{rel_path} -->"
                    )
                continue
            rendered = f"{source.mount}/{rel_path}".replace("\\", "/")
            if rendered not in rendered_paths:
                rendered_paths.add(rendered)
                lines.append(f"@{rendered}")

    if extra_imports:
        lines.append("")
        for path in extra_imports:
            normalized = path.replace("\\", "/")
            if normalized in rendered_paths:
                continue
            rendered_paths.add(normalized)
            lines.append(f"@{normalized}")

    lines.append("")
    imports_path.write_text("\n".join(lines), encoding="utf-8")
    return imports_path
